### ISSUE TITLE
GT2 Belt Tension Meter

### ISSUE THREAD

**Issue by skyaee** [Diyshift/3D-Printer#2]
Hello, ALTERNATIVE CALIBRATION, is there any picture demonstration, and the operation method of text writing, I don't quite understand, thank you.

**Comment by Diyshift** [comment]
Hi, I will put this on my to do list. Thanks for the heads up!

**Comment by Diyshift** [comment]
Image added to instructions. let me know if this helps clarify the instructions.

**Comment by skyaee** [comment]
> 图像已添加到说明中。让我知道这是否有助于澄清说明。图像已添加到说明中。让我知道这是否有助于澄清说明。

Thank you very much, the pictures are self-explanatory. very helpful.
