### ISSUE TITLE
BFI gears incorrect bolt type

### ISSUE THREAD

**Issue by EricZimmerman** [Diyshift/3D-Printer#5]
readme says

`Glue two larger gears to the heads of your M5x40 BHCS using superglue`

but they are SHCS and should be M5x30 from what i can tell

**Comment by Diyshift** [comment]
Thanks for the heads up! You are correct the main screws for Trident are indeed SHCS. Should be 40mm length for trident. 30mm BHCS would be for V2 according to the BFI git.

**Comment by EricZimmerman** [comment]
I am on a 2.4. Very nice mod.
